### PR TITLE
V1.5

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13)

### CODE REVIEW

**Review by andyb3 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13)* status: all files reviewed, 7 unresolved discussions (waiting on @aledj2)

___
*[.gitmodules, line 3 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyT8-IDuva6X6-FPPV:-LvyT8-J2zZ5RJIi6m-z:b-5e1ms0) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/.gitmodules#L3)):*
> ```gitconfig
> [submodule "resources/home/dnanexus/RPKM"]
> 	path = resources/home/dnanexus/RPKM
> 	url = https://github.com/moka-guys/RPKM.git
> ```

Not seen a .gitmodules file before. What does it do?
___
*[dxapp.json, line 29 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyTR0r5jpzmpAndUdk:-LvyTR0r5jpzmpAndUdl:b7ofvik) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/dxapp.json#L29)):*
> ```JSON
>       "name": "bamfile_pannumbers",
>       "label": "bamfile_pannumbers",
>       "help": "comma seperated string on Pannumbers found within the BAM file name",
> ```

typo seperated -> separated
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyTy552GbEkZJwhc11:-LvyTy552GbEkZJwhc12:b-z42sa8) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/README.md#L21)):*
> ```Markdown
> * A project in which to find BAM files
>   * BAM files must be found in /output/
>   * This version of the app downloads BAM files before they preprocessing has been performed (not the refined.bams)
> ```

typo `before they preprocessing has been performed` -> `before preprocessing has been performed`
___
*[README.md, line 24 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyUAIn2sxwkRlj0RXt:-LvyUAIn2sxwkRlj0RXu:b4g776s) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/README.md#L24)):*
> ```Markdown
>   * A comma seperated string of Pan number(s) describing which BAM files should be downloaded.
>   * The BAMfiles will be named using the variant caling pan number.
>   * The RPKM bed file has a different panel number. 
> ```

white space at end
___
*[README.md, line 31 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyUsdCDzsbdVg2CDE6:-LvyUsdCDzsbdVg2CDE7:b-k5e6q2) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/README.md#L31)):*
> ```Markdown
> 
> ## What does this app output?
> Within a folder named conifer_output a folder is created using the Pannumber of the RPKM bedfile. Within this folder the following files are created:
> ```

Pannumber -> pan number (to be consistent with above)
___
*[resources/home/dnanexus/RPKM, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyV0hBDbqRttr7vQXO:-LvyV0hBDbqRttr7vQXP:b2s2ria) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/resources/home/dnanexus/RPKM#L1)):*
> ```
> Subproject commit 8b702f60ca2cd66ae5fef6ae0764a1beb4c4748d
> ```

What is this?
___
*[src/code.sh, line 42 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyW1zB2HLwlY6fhY1l:-LvyW1zB2HLwlY6fhY1m:b-qc211d) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/src/code.sh#L42)):*
> ```Shell
> filecount="$(ls *001.ba* | grep . -c)"
> if (( $filecount < 6 )); then
> 	echo "LESS THAN THREE BAM FILES FOUND FOR THIS PAN NUMBER" 1>&2
> ```

Given that there may be multiple panel numbers, does error message need re-wording slightly? Maybe just something like
"LESS THAN THREE BAM FILES FOUND FOR SELECTED PAN NUMBERS"

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13)* status: all files reviewed, 7 unresolved discussions (waiting on @andyb3)

___
*[.gitmodules, line 3 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyT8-IDuva6X6-FPPV:-Lvye5te-e7hp4XUsbe1:b99ykqe) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/.gitmodules#L3)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Not seen a .gitmodules file before. What does it do?
</blockquote></details>

As discussed the app now contains the cloned code of another github repo. This has been included as a submodule, his file seems to link the cloned repo to the location within this repo. there is a file at this cloned location contaning the SHA1 of the commit which should be checked out
___
*[dxapp.json, line 29 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyTR0r5jpzmpAndUdk:-Lvye5b33g822znybltC:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/dxapp.json#L29)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

typo seperated -> separated
</blockquote></details>

Done.
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyTy552GbEkZJwhc11:-LvyebtD4HHbBhAqqaAq:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/README.md#L21)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

typo `before they preprocessing has been performed` -> `before preprocessing has been performed`
</blockquote></details>

Done.
___
*[README.md, line 24 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyUAIn2sxwkRlj0RXt:-Lvyed8S3m2bGdY7Y_pb:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/README.md#L24)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

white space at end
</blockquote></details>

Done.
___
*[README.md, line 31 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyUsdCDzsbdVg2CDE6:-LvyediW2ZZc1sKPtBUM:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/README.md#L31)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Pannumber -> pan number (to be consistent with above)
</blockquote></details>

Done.
___
*[resources/home/dnanexus/RPKM, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyV0hBDbqRttr7vQXO:-LvyeefGBHsc0ywytt9O:b7a5lbx) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/resources/home/dnanexus/RPKM#L1)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

this dictates which timepoint of the submodule should be used. this SHA1 relates to release v1.0
___
*[src/code.sh, line 42 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-LvyW1zB2HLwlY6fhY1l:-Lvyes8R9_uWzb5uBCNQ:bb7f2mf) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/8a4e7430d4c6b81e2c2b85d6424d270392318b46/src/code.sh#L42)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Given that there may be multiple panel numbers, does error message need re-wording slightly? Maybe just something like
"LESS THAN THREE BAM FILES FOUND FOR SELECTED PAN NUMBERS"
</blockquote></details>

done

**Review by andyb3 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13#-:-Lvyh3ZgERsMAXl1Z7hd:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @andyb3)

**Review by andyb3 — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/13)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
