### PR TITLE
Specify version zlib. Upgrade to Ubutnu 14.04.

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_rpkm/7)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7#-:-L5hYhXNHrXBgjJvhQB1:bweg3f8)*

**Comment by andyb3** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[dxapp.json, line 10 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7#-L5hYtlUkNgYQksSiUi5:-L5hYtlUkNgYQksSiUi6:b-t6jk67) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/9e4d8a39571942ef127d5efa4f5fdd81c295354b/dxapp.json#L10)):*
> ```JSON
>   "properties": {
>     "github release": "v1.2"
>   },
> ```

Not sure why this has moved position. This is where it was in the JSON when I did dx get from 001

---

*[dxapp.json, line 62 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7#-L5hYdBLJZEEHY0v74JK:-L5hYdBLJZEEHY0v74JL:b-cffip2) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/9e4d8a39571942ef127d5efa4f5fdd81c295354b/dxapp.json#L62)):*
> ```JSON
>         "main": {
>           "instanceType": "mem1_ssd1_x4"
>         }
> ```

FYI I didn't add this. It was already in the JSON when I did dx get from 001. I'm guessing this was automatically added by DNAnexus?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7)*

**Comment by aledj2** [comment]
Could you also update the version number in the readme header please

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7#-:-L5hZ1fVAPgng8jNZRGs:bgu6ewo)*

**Comment by aledj2** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[dxapp.json, line 10 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7#-L5hYtlUkNgYQksSiUi5:-L5hZI3thGydmiaRcwrd:b-hhchey) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/9e4d8a39571942ef127d5efa4f5fdd81c295354b/dxapp.json#L10)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Not sure why this has moved position. This is where it was in the JSON when I did dx get from 001
</blockquote></details>

yea, like below, I think when an app is built/or `dx get` this json file is rearranged slightly.

---

*[dxapp.json, line 62 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7#-L5hYdBLJZEEHY0v74JK:-L5hZCVWnh5Lk6xREm4w:b-z3asq5) ([raw file](https://github.com/moka-guys/dnanexus_rpkm/blob/9e4d8a39571942ef127d5efa4f5fdd81c295354b/dxapp.json#L62)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

FYI I didn't add this. It was already in the JSON when I did dx get from 001. I'm guessing this was automatically added by DNAnexus?
</blockquote></details>

yea, have noticed a few things like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_rpkm/7#-:-L5hZhyYveqlNZnOA5J-:bnfp4nl)*

**Pull request merged**
